@startuml
actor User
participant Ui
participant Parser
participant SearcherParser

User -> Ui : "search c/"
Ui -> Parser : parse("search c/")
Parser -> SearcherParser : parse("search c/")
alt searchTerm is empty
    SearcherParser --> Parser : throw JobPilotException
    Parser -> Ui : showError("Search value cannot be empty!")
    Ui --> User : error displayed
end
@enduml