' @@author Aswin-RajeshKumar
@startuml
skinparam Style strictuml
skinparam SequenceMessageAlignment center

actor User
participant ":Ui" as Ui
participant ":CommandRunner" as CommandRunner
participant ":StatusParser" as StatusParser
participant "app:Application" as Application

User -> Ui : "status 1 s/OFFER note/Negotiate salary"
activate Ui

Ui -> CommandRunner : run("status 1 s/OFFER note/Negotiate salary")
activate CommandRunner

CommandRunner -> StatusParser : parse("1 s/OFFER note/Negotiate salary")
activate StatusParser
StatusParser --> CommandRunner : ParsedCommand(0, "OFFER", "Negotiate salary")
deactivate StatusParser

CommandRunner -> Application : setStatus("OFFER")
activate Application
Application --> CommandRunner
deactivate Application

CommandRunner -> Application : setNotes("Negotiate salary")
activate Application
Application --> CommandRunner
deactivate Application

CommandRunner -> Ui : showStatusUpdated(app)
deactivate CommandRunner

Ui --> User : "Updated Status: ... OFFER (Note: Negotiate salary)"
deactivate Ui
@enduml